#!/bin/bash
# ============================================================
#  Code Claw VSCode 扩展 — 一键打包脚本
#  用法:
#    ./build.sh              # 标准打包（不含日志统计）
#    ./build.sh --with-stats # 包含日志统计功能（从 .env 读取 URL）
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# 解析参数
WITH_STATS=false
for arg in "$@"; do
    case "$arg" in
        --with-stats) WITH_STATS=true ;;
    esac
done

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info()  { echo -e "${CYAN}[INFO]${NC}  $1"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ============================================================
# 1. 环境检查
# ============================================================
log_info "检查环境..."

# Node.js
if ! command -v node &> /dev/null; then
    log_error "未找到 Node.js，请先安装 (>= 18)"
    exit 1
fi
NODE_VERSION=$(node -v)
log_ok "Node.js ${NODE_VERSION}"

# npm
if ! command -v npm &> /dev/null; then
    log_error "未找到 npm"
    exit 1
fi
log_ok "npm $(npm -v)"

# ============================================================
# 2. 清理旧产物
# ============================================================
log_info "清理旧产物..."
rm -rf out
rm -f codeclaw-vscode-*.vsix
log_ok "已清理 out/ 和 *.vsix"

# ============================================================
# 3. 安装依赖
# ============================================================
log_info "安装依赖..."
npm install 2>&1 | tail -1
log_ok "依赖安装完成"

# ============================================================
# 4. 检查关键文件
# ============================================================
log_info "检查关键文件..."
REQUIRED_FILES=(
    "src/extension.ts"
    "src/panel.ts"
    "src/statusbar.ts"
    "package.json"
    "tsconfig.json"
    "icon.svg"
)
MISSING=0
for f in "${REQUIRED_FILES[@]}"; do
    if [ ! -f "$f" ]; then
        log_error "缺少文件: $f"
        MISSING=$((MISSING + 1))
    fi
done
if [ $MISSING -gt 0 ]; then
    log_error "缺少 $MISSING 个必要文件，请检查项目完整性"
    exit 1
fi
log_ok "关键文件检查通过"

# ============================================================
# 5. TypeScript 类型检查（编译但不输出，仅检查类型）
# ============================================================
log_info "TypeScript 类型检查..."
if npx tsc --noEmit 2>&1; then
    log_ok "类型检查通过"
else
    log_warn "类型检查有警告/错误，但不影响 esbuild 打包"
fi

# ============================================================
# 5.5 生成 stats-config.ts（日志统计配置）
# ============================================================
if [ "$WITH_STATS" = true ]; then
    log_info "生成日志统计配置 (--with-stats)..."
    if [ ! -f .env ]; then
        log_error "未找到 .env 文件，--with-stats 需要 .env 中配置 STATS_URL"
        exit 1
    fi
    STATS_URL=$(grep -E '^STATS_URL=' .env | head -1 | cut -d'=' -f2- | tr -d '"' | tr -d "'" | xargs)
    if [ -z "$STATS_URL" ]; then
        log_error ".env 中未找到 STATS_URL 配置"
        exit 1
    fi
    # 写入带 URL 的配置
    cat > src/stats-config.ts << STATS_EOF
// Auto-generated by build.sh --with-stats
export const STATS_URL = '${STATS_URL}';
STATS_EOF
    log_ok "日志统计已启用: ${STATS_URL}"
else
    log_info "日志统计: 已禁用（使用 --with-stats 启用）"
    # 写入空配置（no-op）
    cat > src/stats-config.ts << STATS_EOF
// Auto-generated by build.sh (default build, stats disabled)
export const STATS_URL = '';
STATS_EOF
fi

# ============================================================
# 6. esbuild 打包（bundle 所有依赖为单文件）
# ============================================================
log_info "esbuild 打包..."
npx esbuild ./src/extension.ts \
    --bundle \
    --outfile=out/extension.js \
    --external:vscode \
    --format=cjs \
    --platform=node \
    --minify \
    --sourcemap

if [ ! -f out/extension.js ]; then
    log_error "esbuild 打包失败，未生成 out/extension.js"
    exit 1
fi
FILE_SIZE=$(du -h out/extension.js | cut -f1)
log_ok "打包完成: out/extension.js (${FILE_SIZE})"

# ============================================================
# 7. 复制 Claude Code CLI 到 out/（内置，无需系统安装）
# ============================================================
log_info "复制 Claude Code CLI..."
mkdir -p out/claude-code
CLAUDE_CLI_SRC="node_modules/@anthropic-ai/claude-agent-sdk/cli.js"
if [ -f "$CLAUDE_CLI_SRC" ]; then
    cp "$CLAUDE_CLI_SRC" out/claude-code/cli.js
    CLI_SIZE=$(du -h out/claude-code/cli.js | cut -f1)
    log_ok "Claude Code CLI 已复制: out/claude-code/cli.js (${CLI_SIZE})"
else
    log_error "未找到 Claude Code CLI: $CLAUDE_CLI_SRC"
    log_error "请确认已执行 npm install 且 claude-agent-sdk 依赖完整"
    exit 1
fi

# ============================================================
# 8. 验证打包结果
# ============================================================
log_info "验证打包结果..."
if grep -q "claude" out/extension.js; then
    log_ok "Anthropic SDK 已打包进 extension.js"
else
    log_warn "未检测到 Claude SDK，请检查依赖"
fi
if [ -f out/claude-code/cli.js ]; then
    log_ok "Claude Code CLI 已就绪 (out/claude-code/cli.js)"
else
    log_error "Claude Code CLI 未就绪"
    exit 1
fi

# ============================================================
# 9. 生成 VSIX
# ============================================================
log_info "生成 VSIX..."

# 根据是否启用统计决定文件名后缀
if [ "$WITH_STATS" = true ]; then
    # 如果启用了日志统计，则在文件名中添加"内部版"后缀
    BASE_NAME=$(node -p "require('./package.json').name.replace('@', '').replace('/', '-')")
    VERSION=$(node -p "require('./package.json').version")
    VSIX_FILE="${BASE_NAME}-${VERSION}-内部版.vsix"
    npx @vscode/vsce package --out "$VSIX_FILE" --allow-missing-repository 2>&1
else
    # 否则按默认方式生成
    npx @vscode/vsce package --allow-missing-repository 2>&1
    VSIX_FILE=$(ls codeclaw-vscode-*.vsix 2>/dev/null | head -1)
fi

if [ -z "$VSIX_FILE" ] || [ ! -f "$VSIX_FILE" ]; then
    log_error "VSIX 打包失败"
    exit 1
fi

VSIX_SIZE=$(du -h "$VSIX_FILE" | cut -f1)
log_ok "VSIX 生成: ${VSIX_FILE} (${VSIX_SIZE})"

# ============================================================
# 10. 完成
# ============================================================
echo ""
echo -e "${GREEN}══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ 打包成功！${NC}"
echo -e "${GREEN}══════════════════════════════════════════════════${NC}"
echo ""
echo "  产物: ${VSIX_FILE}"
echo "  大小: ${VSIX_SIZE}"
echo "  日志统计: $([ "$WITH_STATS" = true ] && echo '已启用' || echo '未启用')"
echo ""
echo -e "  ${CYAN}安装方式:${NC}"
echo "    code --install-extension ${VSIX_FILE}"
echo "    或 VSCode 中 Ctrl+Shift+P → Extensions: Install from VSIX..."
echo ""
echo -e "  ${CYAN}卸载方式:${NC}"
echo "    code --uninstall-extension Sansec.codeclaw-vscode"
echo ""
